### ISSUE TITLE
PHP 7.1 Support

### ISSUE THREAD

**Issue by allrude** [aleron75/mage2hints#3]
[InvalidArgumentException]                                                                                 
  Package aleron75/mage2hints at version  has a PHP requirement incompatible with your PHP version (7.1.14)

Got other Mag2 extensions that require 7.1.x, would love to use /test this

**Comment by aleron75** [comment]
Hi,
just added compatibility directive with 7.1 & 7.2, check it out and let me know it this solves your issue.

Cheers
